### ISSUE TITLE
tft35 v3 errors

### ISSUE THREAD

**Issue by Kscott73** [bigtreetech/BIGTREETECH-TFT35-V3.0#90] opened 2020-11-07 21:39 UTC
firmware: tft35_v3.0.26 apr 11 2020
button pics  are labeled wrong  and coordinates are wrong - home: is 300,310,400
(moves in the direction of button pics

![btttft35](https://user-images.githubusercontent.com/73906818/98451854-dbc4bc00-2117-11eb-9355-bf4ae19504df.jpg)

**Comment by oldman4U** [comment] 2020-11-07 22:16
Hi.

Do you think this is a hardware issue?

**Comment by Kscott73** [comment] 2020-11-08 00:27
dont think so, movement is correct to button pics, button labels are wrong

**Comment by oldman4U** [comment] 2020-11-08 05:12
Software related issues should be started using the software related repository. Update to a firmware from this week and see if this solves the problem.

**Comment by oldman4U** [comment] 2020-11-08 21:09
This is how it looks with an actual firmware.

![image](https://user-images.githubusercontent.com/54359396/98484331-fd549f00-220e-11eb-9c3f-e9e11f712bfa.jpeg)

**Comment by Kscott73** [comment] 2020-11-09 03:16
tried the new firmware, didn't work
the x and z labels are incorrect, along with the coordinates
when press home, it moves in right direction but coordinates are 300,300,400

**Comment by oldman4U** [comment] 2020-11-09 08:11
Attach the config.ini (.CUR), which you have been uploading to the TFT.

**Comment by oldman4U** [comment] 2020-11-09 14:50
The problem is, that you have selected Classic Mode in Config.ini and not Unified Mode like I have. Changing this is config.ini will solve the problem.

**Comment by Kscott73** [comment] 2020-11-09 15:02
firmware uploaded, it did save.. i changed the logo bmp
problems are still there


[config.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5511355/config.zip)

**Comment by oldman4U** [comment] 2020-11-09 15:58
Take a picture from the main screen, from the Move screen and the Info screen and attach it here, please.

**Comment by oldman4U** [comment] 2020-11-09 16:14
And you sent me 2 files with the extension .CUR, but the config is still .ini... Has the config.ini been updated during firmware update?

**Comment by Kscott73** [comment] 2020-11-09 16:36
![IMG_20201109_112420](https://user-images.githubusercontent.com/73906818/98568988-b6eb5880-227f-11eb-8227-54058ed205a1.jpg)
![IMG_20201109_112410](https://user-images.githubusercontent.com/73906818/98568993-b81c8580-227f-11eb-9266-f473f655ae63.jpg)
![IMG_20201109_112358](https://user-images.githubusercontent.com/73906818/98568998-b94db280-227f-11eb-82c1-4c9bb4aaeaf3.jpg)

**Comment by oldman4U** [comment] 2020-11-09 16:38
The firmware is older than old.

Read the ReadMe at this page: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

Do what's described there and let me know.

**Comment by Kscott73** [comment] 2020-11-09 20:14
i've deleted all tft files, zip files
re-downloaded https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware.git
i've changed to classic bmp&fonts
sd card:
[BIGTREE_TFT35_V3.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5513046/BIGTREE_TFT35_V3.0.26.x.zip)

**Comment by Kscott73** [comment] 2020-11-09 20:16
it started off great.
error:
found outdated data:
insert the SD with the required files and press reset to update

**Comment by oldman4U** [comment] 2020-11-09 20:49
Outdated data is a good sign.

Make a picture and attach it or check with data is outdated on screen.

**Comment by oldman4U** [comment] 2020-11-09 20:50
The content of your SD card looks good in general.

**Comment by Kscott73** [comment] 2020-11-09 21:03
![IMG_20201109_160207](https://user-images.githubusercontent.com/73906818/98596177-127c0d00-22a5-11eb-9e2c-b78cc6e354cc.jpg)

**Comment by Kscott73** [comment] 2020-11-09 21:28
why am i getting outdated files, im downloading from straight from github
[BIGTREE_TFT35_V3.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5513374/BIGTREE_TFT35_V3.0.26.x.zip)
here is the cur files

**Comment by oldman4U** [comment] 2020-11-09 21:57
Uii, this looks strange.

It should look a bit like this:
<img width="394" alt="Screenshot 2020-11-09 at 22 48 34" src="https://user-images.githubusercontent.com/54359396/98600661-3b6cc400-22de-11eb-93b1-a55514dfbedc.png">

Your .CUR files look good, so everything which can be updated has been updated, but somehow this ended in a corrupted firmware.

I believe the precompiled firmware is somehow corrupted. Please take the attached file, unzip it and change the TXT to bin. Put it on the SD Card and update the firmware again.

Please let me know

[BIGTREE_TFT35_V3.0.26.x.TXT.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5513501/BIGTREE_TFT35_V3.0.26.x.TXT.zip)

**Comment by Kscott73** [comment] 2020-11-10 00:26
OK
1) Format SD
2) Unzip
3) Copy File & Rename Extension
4) Eject SD

I now have a bigger problem
[TFT35.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5514002/TFT35.zip)


(https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5513986/TFT35.zip)
![IMG_20201109_191641](https://user-images.githubusercontent.com/73906818/98611936-056d1700-22c1-11eb-8c0d-207c8da51fc5.jpg)

**Comment by Kscott73** [comment] 2020-11-10 01:53
last try before calling it a night
used your file
[BIGTREE_TFT35_V3.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/files/5514244/BIGTREE_TFT35_V3.0.26.x.zip)
can't use touch screen and switching other mode is just a black screen
![IMG_20201109_204911](https://user-images.githubusercontent.com/73906818/98617549-3e12ed80-22cd-11eb-9975-ccb9b959152a.jpg)

**Comment by oldman4U** [comment] 2020-11-10 12:49
Make a textfile named reset.txt, put it on sd card insert into tft and press reset knob.

**Comment by Kscott73** [comment] 2020-11-10 14:08
yes, i have touch screen and more buttons..
now its just stallguard giving me problems
thank you


![IMG_20201110_085610__01](https://user-images.githubusercontent.com/73906818/98684372-186cff00-2334-11eb-87d1-a86a611f631b.jpg)

**Comment by oldman4U** [comment] 2020-11-11 09:43
The firmware is still old, maybe you want to update it.

Please close this ticket, thank you.

**Closed as completed** 2020-11-13 02:57 UTC
