### ISSUE TITLE
TFT35 print slows down after Probe offset change

### ISSUE THREAD

**Issue by AhmedTheGeek** [bigtreetech/BIGTREETECH-TFT35-V3.0#128] opened 2021-05-23 10:30 UTC
To reproduce:

- Initiate probe offset procedure.
- Save the new probe offset.
- Start a gcode file with G29 in it.
- Once the G29 is finished the print speed slows down a lot.

The issue is reproducible every time.

**Comment by radek8** [comment] 2021-05-24 21:08
I assume you are using an encoder to change the value ...
Rotating the encoder in touch mode changes the print speed in Marlin.

Write what your HW and SW configuration is
For some configurations, the problem is fixed in the new FW.
Thank you

**Comment by AhmedTheGeek** [comment] 2021-05-25 11:42
@radek8 Yeah right the last few times I did this I was using the encoder.

HW:
- Ender 3 Pro.
- SKR Mini E3 V2.
- TFT 35 E3 v3.0.

SW:
- TFT35_E3_V3.0.27.X May 17 2021 Update.
- Marlin bugfix-2.0.x Mar 18 2021 Update.

**Comment by radek8** [comment] 2021-05-25 12:21
Yes, that's your problem.
There is no fix for this SKRmini board.

There are 4 possible solutions. Choose which suits you

1. Do not use the encoder in touch mode.
2. Do not use simulated Marlin mode on TFT (disconnect 10pin cable).
3. In Marlin, turn off the return to the status screen. The speed change only takes place on the status screen. After turning on the printers, just one click on the encoder and then you can rotate the encoder as you wish. But you can't click!
4. modification of the definition of pins in Marlin and stretching of another wire between SKR and TFT. Theoretically it should work, but I haven't tried it. I don't have a SKR mini to try it out. The most complicated but the best solution.

**Comment by oldman4U** [comment] 2021-05-25 21:04
Or buy a mainboard which connects with 2 EXP cables😁

**Comment by radek8** [comment] 2021-07-18 07:01
If the problem is resolved, close the ticket. Thank you.

**Closed as completed** 2021-07-18 18:32 UTC
